server:
  port: 8888

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@127.0.0.1:8761/eureka/



spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangzybj/spring-scapital-cloud.git
          search-paths: ../config-repo
  rabbitmq:
    host: rabbitmq

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}


#  server.port=1111
#  #spring.cloud.config.server.git.uri=https://git.oschina.net/zhou666/spring-cloud-7simple.git
#  #spring.cloud.config.server.git.searchPaths=cloud-config-repo
#  spring.application.name=cloud-config-server
#  spring.cloud.config.server.native.searchLocations=../cloud-config-repo
#  spring.profiles.active=native
#  eureka.instance.hostname=192.168.2.17
#  eureka.client.serviceUrl.defaultZone=http\://${eureka.instance.hostname}\:8888/eureka/